server:
  port: 8000
spring:
  autoconfigure:
    exclude:
      - org.activiti.spring.boot.SecurityAutoConfiguration
      - org.activiti.spring.boot.EndpointAutoConfiguration
      - org.activiti.spring.boot.JpaProcessEngineAutoConfiguration
      - org.activiti.spring.boot.DataSourceProcessEngineAutoConfiguration
      - org.activiti.spring.boot.RestApiAutoConfiguration
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud3?serverTimezone=UTC&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  config-location: classpath:config/mybatis-config.xml
